name: Check version bump
on:
  pull_request:
    branches: "main"
    paths-ignore:
      - .gitignore
      - LICENSE
      - README.md
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true
jobs:
  check-version-bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: del-systems/check-if-version-bumped@v1
