name: Test Node.js
on:
  push:
    branches: "main"
    paths-ignore:
      - .gitignore
      - LICENSE
      - README.md
      - .github/**
      - "!.github/workflows/test-nodejs.yml"
  pull_request:
    paths-ignore:
      - .gitignore
      - LICENSE
      - README.md
      - .github/**
      - "!.github/workflows/test-nodejs.yml"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true
jobs:
  test-nodejs:
    strategy:
      matrix:
        node-version: ["16", "18", "20"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm ci
      - run: npm test
  test-nodejs-mismatched-version:
    strategy:
      matrix:
        node-version: ["16", "18", "20"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
      - run: npm ci
      # Run just the build step in Node.js v20
      - run: npm run pretest
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      # Now run the tests in Node.js v16, v18, and v20
      - run: npm test --ignore-scripts
